### ISSUE TITLE
Install without admin rights

### ISSUE THREAD

**Issue by roti** [marchaesen/vcxsrv#8]
It would be nice if the installer would work without admin rights.

It managed to get it running like this:
```
set __COMPAT_LAYER=RunAsInvoker
start vcxsrv-64.21.1.10.0.installer.exe
```
But the shortcuts were not created, for obvious reasons:
```
Error creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\VcXsrv\Uninstall VcXsrv.lnk
Error creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\VcXsrv\XLaunch.lnk
```

**Comment by dZ8Lx9OwX** [comment]
I thought this might help you.
[Making Portable](https://sourceforge.net/p/vcxsrv/wiki/Making%20Portable/)

**Comment by marchaesen** [comment]
-noadmin.exe installers added in 21.1.13 release
